### ISSUE TITLE
Hello, ur blog is so senior.

### ISSUE THREAD

**Issue by jialudev** [Jacky-Summer/personal-blog#1]
can i have communicate with u in wechat?

**Comment by Jacky-Summer** [comment]
> can i have communicate with u in wechat?

😂 Do you have any questions for me? you can leave me your email address first.

**Comment by jialudev** [comment]
email is to slow.

**Comment by Henery002** [comment]
ni hai shi yinggai shiyong chinese lai jiaoliu, bijing nide english taitaitai chinenglish.
